-- place to put the queries we want to test
-- TOP-K USERS
SELECT USR.NAME AS USER_NAME, PROD.NAME AS PRODUCT_NAME, COALESCE(SUM(O.PRICE), 0) AS CELL_SUM,
USR.USER_SUM AS ROW_SUM, PROD.PRODUCT_SUM AS COLUMN_SUM
FROM (
SELECT U.ID, U.NAME, SUM(O.PRICE) AS USER_SUM
FROM USERS U, ORDERS O
WHERE O.USER_ID = U.ID
GROUP BY U.ID, U.NAME
ORDER BY USER_SUM DESC LIMIT 20
) USR
CROSS JOIN (
SELECT P.ID, P.NAME, SUM(O.PRICE) AS PRODUCT_SUM
FROM PRODUCTS P, ORDERS O
WHERE O.PRODUCT_ID = P.ID
GROUP BY P.ID, P.NAME
ORDER BY PRODUCT_SUM DESC LIMIT 10
) PROD
LEFT JOIN ORDERS O
ON O.USER_ID = USR.ID AND O.PRODUCT_ID = PROD.ID
GROUP BY USR.ID, PROD.ID, USR.NAME, PROD.NAME, USR.USER_SUM, PROD.PRODUCT_SUM
ORDER BY PROD.PRODUCT_SUM DESC;